// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdlgmwltivhdggzylrfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkbGdtd2x0aXZoZGdnenlscmZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5ODI3ODQsImV4cCI6MjA4ODU1ODc4NH0.uFtvML0nDBWXMAK98e1ZNZeWfw4JdX8b7GCe0_4yors";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});